# -*- coding: utf-8 -*-
from __future__ import unicode_literals

country_dict = {
    'República del Perú': 'peru',
    'the Abode of Peace': 'brunei',
    'AE': 'united arab emirates',
    'AF': 'afghanistan',
    'AG': 'antigua and barbuda',
    'AI': 'anguilla',
    'AL': 'albania',
    'AM': 'armenia',
    'AO': 'angola',
    'AR': 'argentina',
    'AS': 'american samoa',
    'AT': 'austria',
    'AU': 'australia',
    'AW': 'aruba',
    'AZ': 'azerbaijan',
    'Afġānistān': 'afghanistan',
    'Al-Jumhūrīyah Al-Libnānīyah': 'lebanon',
    'Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah': 'syria',
    'Al-Mamlakah al-Maġribiyah': 'morocco',
    'Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah': 'saudi arabia',
    'Algérie': 'algeria',
    'Amelika Sāmoa': 'american samoa',
    'American Samoa': 'american samoa',
    'Amerika Sāmoa': 'american samoa',
    'Angola': 'angola',
    'Anguilla': 'anguilla',
    'Antigua and Barbuda': 'antigua and barbuda',
    'Aolepān Aorōkin M̧ajeļ': 'marshall islands',
    'Aotearoa': 'new zealand',
    'Arab Republic of Egypt': 'egypt',
    'Argentina': 'argentina',
    'Argentine Republic': 'argentina',
    'Aruba': 'aruba',
    'Australia': 'australia',
    'Azərbaycan': 'azerbaijan',
    'Azərbaycan Respublikası': 'azerbaijan',
    'BA': 'bosnia and herzegovina',
    'BB': 'barbados',
    'BD': 'bangladesh',
    'BE': 'belgium',
    'BF': 'burkina faso',
    'BG': 'bulgaria',
    'BH': 'bahrain',
    'BI': 'burundi',
    'BJ': 'benin',
    'BM': 'bermuda',
    'BN': 'brunei',
    'BO': 'bolivia',
    'BR': 'brazil',
    'BS': 'the bahamas',
    'BT': 'bhutan',
    'BW': 'botswana',
    'BY': 'belarus',
    'BZ': 'belize',
    'Bahamas': 'the bahamas',
    'Bailiwick of Guernsey': 'guernsey',
    'Bailiwick of Jersey': 'jersey',
    'Bailliage de Guernesey': 'guernsey',
    'Bailliage de Jersey': 'jersey',
    'Bailliage dé Jèrri': 'jersey',
    'Barbados': 'barbados',
    'Belgie': 'belgium',
    'Belgien': 'belgium',
    'Belgique': 'belgium',
    'België': 'belgium',
    'Belize': 'belize',
    'Belorussiya': 'belarus',
    'Beluu er a Belau': 'palau',
    'Bermuda': 'bermuda',
    'Bharat Ganrajya': 'india',
    'Bhārat': 'india',
    'Bielaruś': 'belarus',
    'Bolivarian Republic of Venezuela': 'venezuela',
    'Bolivia': 'bolivia',
    'Bosna i Hercegovina': 'bosnia and herzegovina',
    'Bosnia-Herzegovina': 'bosnia and herzegovina',
    'Botswana': 'botswana',
    'Brasil': 'brazil',
    'British Indian Ocean Territory': 'british indian ocean territory',
    'Buliwya': 'bolivia',
    'Buliwya Mamallaqta': 'bolivia',
    'Bundesrepublik Deutschland': 'germany',
    'Burkina Faso': 'burkina faso',
    'Burundi': 'burundi',
    'Bénin': 'benin',
    'CA': 'canada',
    'CC': 'cocos (keeling) islands',
    'CD': 'democratic republic of the congo',
    'CF': 'central african republic',
    'CG': 'republic of the congo',
    'CH': 'switzerland',
    'CI': 'ivory coast',
    'CK': 'cook islands',
    'CL': 'chile',
    'CM': 'cameroon',
    'CN': 'china',
    'CO': 'colombia',
    'CR': 'costa rica',
    'CU': 'cuba',
    'CV': 'cape verde',
    'CX': 'christmas island',
    'CY': 'cyprus',
    'CZ': 'czech republic',
    'Cabo Verde': 'cape verde',
    'Cameroon': 'cameroon',
    'Canada': 'canada',
    'Cayman Islands': 'cayman islands',
    'Central African Republic': 'central african republic',
    'Chile': 'chile',
    'Chosŏn Minjujuŭi Inmin Konghwaguk': 'north korea',
    'Christmas Island': 'christmas island',
    'Co-operative Republic of Guyana': 'guyana',
    'Cocos (Keeling) Islands': 'cocos (keeling) islands',
    'Collectivité territoriale de Saint-Pierre-et-Miquelon': 'saint pierre and miquelon',
    'Colombia': 'colombia',
    'Commonwealth of Dominica': 'dominica',
    'Commonwealth of Puerto Rico': 'puerto rico',
    'Commonwealth of the Bahamas': 'the bahamas',
    'Commonwealth of the Northern Mariana Islands': 'northern mariana islands',
    'Congo-Brazzaville': 'republic of the congo',
    'Congo-Kinshasa': 'democratic republic of the congo',
    'Cook Islands': 'cook islands',
    'Costa Rica': 'costa rica',
    'Cuba': 'cuba',
    "Côte d'Ivoire": 'ivory coast',
    'Cộng hòa Xã hội chủ nghĩa Việt Nam': 'vietnam',
    'DE': 'germany',
    'DJ': 'djibouti',
    'DK': 'denmark',
    'DM': 'dominica',
    'DO': 'dominican republic',
    'DR Congo': 'democratic republic of the congo',
    'DRC': 'democratic republic of the congo',
    'DZ': 'algeria',
    'Danmark': 'denmark',
    'Dawlat Iritriyá': 'eritrea',
    'Dawlat Libya': 'libya',
    'Dawlat Qaṭar': 'qatar',
    'Dawlat al-Kuwait': 'kuwait',
    "Democratic People's Republic of Korea": 'north korea',
    'Democratic Republic of São Tomé and Príncipe': 'são tomé and príncipe',
    'Democratic Republic of Timor-Leste': 'east timor',
    'Democratic Socialist Republic of Sri Lanka': 'sri lanka',
    'Department of Mayotte': 'mayotte',
    'Deutschland': 'germany',
    'Dhivehi Raajjeyge Jumhooriyya': 'maldives',
    'Djibouti': 'djibouti',
    'Dominica': 'dominica',
    'Dominique': 'dominica',
    'Dzayer': 'algeria',
    'Département de Mayotte': 'mayotte',
    'EC': 'ecuador',
    'EE': 'estonia',
    'EG': 'egypt',
    'EH': 'western sahara',
    'ER': 'eritrea',
    'ES': 'spain',
    'ET': 'ethiopia',
    'East Timor': 'east timor',
    'Ecuador': 'ecuador',
    'Eesti': 'estonia',
    'Eesti Vabariik': 'estonia',
    'El Salvador': 'el salvador',
    'Ellan Vannin': 'isle of man',
    'Elláda': 'greece',
    'España': 'spain',
    'Estado Libre Asociado de Puerto Rico': 'puerto rico',
    'Estado Plurinacional de Bolivia': 'bolivia',
    'Estados Unidos Mexicanos': 'mexico',
    'FI': 'finland',
    'FJ': 'fiji',
    'FK': 'falkland islands',
    'FM': 'federated states of micronesia',
    'FO': 'faroe islands',
    'FR': 'france',
    'Falkland Islands': 'falkland islands',
    'Federal Democratic Republic of Ethiopia': 'ethiopia',
    'Federal Democratic Republic of Nepal': 'nepal',
    'Federal Republic of Germany': 'germany',
    'Federal Republic of Nigeria': 'nigeria',
    'Federal Republic of Somalia': 'somalia',
    'Federated States of Micronesia': 'federated states of micronesia',
    'Federation of Saint Christopher and Nevis': 'saint kitts and nevis',
    'Federative Republic of Brazil': 'brazil',
    'Fiji': 'fiji',
    'Fijī Gaṇarājya': 'fiji',
    'France': 'france',
    'French Polynesia': 'french polynesia',
    'French Republic': 'france',
    'Færøerne': 'faroe islands',
    'Føroyar': 'faroe islands',
    'Fürstentum Liechtenstein': 'liechtenstein',
    'GA': 'gabon',
    'GB': 'united kingdom',
    'GD': 'grenada',
    'GE': 'georgia',
    'GF': 'french guiana',
    'GG': 'guernsey',
    'GH': 'ghana',
    'GI': 'gibraltar',
    'GL': 'greenland',
    'GM': 'the gambia',
    'GN': 'guinea',
    'GP': 'guadeloupe',
    'GQ': 'equatorial guinea',
    'GR': 'greece',
    'GS': 'south georgia',
    'GT': 'guatemala',
    'GU': 'guam',
    'GW': 'guinea-bissau',
    'GY': 'guyana',
    'Gabon': 'gabon',
    'Gabonese Republic': 'gabon',
    'Gabuuti': 'djibouti',
    'Gabuutih Ummuuno': 'djibouti',
    'Gambia': 'the gambia',
    'Ghana': 'ghana',
    'Gibraltar': 'gibraltar',
    'Grand Duchy of Luxembourg': 'luxembourg',
    'Grand-Duché de Luxembourg': 'luxembourg',
    'Great Britain': 'united kingdom',
    'Grenada': 'grenada',
    'Groussherzogtum Lëtzebuerg': 'luxembourg',
    'Großherzogtum Luxemburg': 'luxembourg',
    'Grønland': 'greenland',
    'Guadeloupe': 'guadeloupe',
    'Guam': 'guam',
    'Guatemala': 'guatemala',
    'Guernsey': 'guernsey',
    'Guiana': 'french guiana',
    'Guinea Ecuatorial': 'equatorial guinea',
    'Guiné-Bissau': 'guinea-bissau',
    'Guinée': 'guinea',
    'Guyana': 'guyana',
    'Guyane': 'french guiana',
    'Guyane française': 'french guiana',
    'Guåhån': 'guam',
    'Gwadloup': 'guadeloupe',
    'Gônôprôjatôntri Bangladesh': 'bangladesh',
    'HK': 'hong kong',
    'HM': 'heard island and mcdonald islands',
    'HN': 'honduras',
    'HR': 'croatia',
    'HT': 'haiti',
    'HU': 'hungary',
    'Hashemite Kingdom of Jordan': 'jordan',
    'Hayastan': 'armenia',
    'Haïti': 'haiti',
    'Heard Island and McDonald Islands': 'heard island and mcdonald islands',
    'Hellenic Republic': 'greece',
    'Holland': 'netherlands',
    'Honduras': 'honduras',
    'Hrvatska': 'croatia',
    'ID': 'indonesia',
    'IE': 'ireland',
    'IL': 'israel',
    'IM': 'isle of man',
    'IN': 'india',
    'IO': 'british indian ocean territory',
    'IQ': 'iraq',
    'IR': 'iran',
    'IS': 'iceland',
    'IT': 'italy',
    'Independen Stet bilong Papua Niugini': 'papua new guinea',
    'Independent State of Papua New Guinea': 'papua new guinea',
    'Independent State of Samoa': 'samoa',
    'Indonesia': 'indonesia',
    'Iritriyā': 'eritrea',
    'Irān': 'iran',
    'Islamic Republic of Iran': 'iran',
    'Islamic Republic of Mauritania': 'mauritania',
    'Islamic Republic of Pakistan': 'pakistan',
    'Island': 'iceland',
    'Islas Malvinas': 'falkland islands',
    'Isle of Man': 'isle of man',
    "Islāmī Jumhūriya'eh Pākistān": 'pakistan',
    'Italia': 'italy',
    'Italian Republic': 'italy',
    'Ivory Coast': 'ivory coast',
    'JE': 'jersey',
    'JM': 'jamaica',
    'JO': 'jordan',
    'JP': 'japan',
    'Jabuuti': 'djibouti',
    'Jamaica': 'jamaica',
    'Jamhuri ya Kenya': 'kenya',
    'Jamhuri ya Muungano wa Tanzania': 'tanzania',
    'Jamhuri ya Uganda': 'uganda',
    'Jamhuuriyadda Federaalka Soomaaliya': 'somalia',
    'Jamhuuriyadda Jabuuti': 'djibouti',
    'Jersey': 'jersey',
    'Jomhuri-ye Eslāmi-ye Irān': 'iran',
    'Jumhūriyyat al-‘Irāq': 'iraq',
    'Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya': 'somalia',
    'Jumhūrīyat as-Sūdān': 'sudan',
    'KE': 'kenya',
    'KG': 'kyrgyzstan',
    'KH': 'cambodia',
    'KI': 'kiribati',
    'KM': 'comoros',
    'KN': 'saint kitts and nevis',
    'KP': 'north korea',
    'KR': 'south korea',
    'KW': 'kuwait',
    'KY': 'cayman islands',
    'KZ': 'kazakhstan',
    'Kalaallit Nunaat': 'greenland',
    'Keeling Islands': 'cocos (keeling) islands',
    'Kenya': 'kenya',
    'Kingdom of Bahrain': 'bahrain',
    'Kingdom of Belgium': 'belgium',
    'Kingdom of Bhutan': 'bhutan',
    'Kingdom of Cambodia': 'cambodia',
    'Kingdom of Denmark': 'denmark',
    'Kingdom of Lesotho': 'lesotho',
    'Kingdom of Morocco': 'morocco',
    'Kingdom of Norway': 'norway',
    'Kingdom of Saudi Arabia': 'saudi arabia',
    'Kingdom of Spain': 'spain',
    'Kingdom of Swaziland': 'swaziland',
    'Kingdom of Sweden': 'sweden',
    'Kingdom of Thailand': 'thailand',
    'Kiribati': 'kiribati',
    'Komori': 'comoros',
    'Kongeriget Danmark': 'denmark',
    'Kongeriket Noreg': 'norway',
    'Kongeriket Norge': 'norway',
    'Koninkrijk België': 'belgium',
    'Konungariket Sverige': 'sweden',
    'Kyrgyz Republic': 'kyrgyzstan',
    'Kyrgyz Respublikasy': 'kyrgyzstan',
    'Kâmpŭchéa': 'cambodia',
    'Ködörösêse tî Bêafrîka': 'central african republic',
    'Königreich Belgien': 'belgium',
    'Kýpros': 'cyprus',
    'Kıbrıs': 'cyprus',
    'Kıbrıs Cumhuriyeti': 'cyprus',
    "Kūki 'Āirani": 'cook islands',
    'LA': 'laos',
    'LB': 'lebanon',
    'LC': 'saint lucia',
    'LI': 'liechtenstein',
    'LK': 'sri lanka',
    'LR': 'liberia',
    'LS': 'lesotho',
    'LT': 'lithuania',
    'LU': 'luxembourg',
    'LV': 'latvia',
    'LY': 'libya',
    'La Réunion': 'réunion',
    'Lao': 'laos',
    "Lao People's Democratic Republic": 'laos',
    'Latvija': 'latvia',
    'Latvijas Republika': 'latvia',
    'Lebanese Republic': 'lebanon',
    'Lefatshe la Botswana': 'botswana',
    'Lesotho': 'lesotho',
    'Liberia': 'liberia',
    'Liechtenstein': 'liechtenstein',
    'Lietuva': 'lithuania',
    'Lietuvos Respublika': 'lithuania',
    'Loktāntrik Ganatantra Nepāl': 'nepal',
    'Luxembourg': 'luxembourg',
    'Lýðveldið Ísland': 'iceland',
    'MA': 'morocco',
    'MC': 'monaco',
    'MD': 'moldova',
    'MG': 'madagascar',
    'MH': 'marshall islands',
    'MK': 'republic of macedonia',
    'ML': 'mali',
    'MN': 'mongolia',
    'MO': 'macau',
    'MP': 'northern mariana islands',
    'MQ': 'martinique',
    'MR': 'mauritania',
    'MS': 'montserrat',
    'MT': 'malta',
    'MU': 'mauritius',
    'MV': 'maldives',
    'MW': 'malawi',
    'MX': 'mexico',
    'MY': 'malaysia',
    'MZ': 'mozambique',
    "Macao Special Administrative Region of the People's Republic of China": 'macau',
    'Madagasikara': 'madagascar',
    'Magyarország': 'hungary',
    'Malawi': 'malawi',
    'Malaysia': 'malaysia',
    'Maldive Islands': 'maldives',
    'Maldives': 'maldives',
    'Mali': 'mali',
    'Malo Saʻoloto Tutoʻatasi o Sāmoa': 'samoa',
    'Malta': 'malta',
    'Mamlakat al-Baḥrayn': 'bahrain',
    'Mann': 'isle of man',
    'Mannin': 'isle of man',
    'Martinique': 'martinique',
    'Matanitu ko Viti': 'fiji',
    'Maurice': 'mauritius',
    'Mayotte': 'mayotte',
    "Medīnat Yisrā'el": 'israel',
    'Mexicanos': 'mexico',
    'Micronesia': 'federated states of micronesia',
    'Moldova': 'moldova',
    'Monaco': 'monaco',
    'Montserrat': 'montserrat',
    'Moçambique': 'mozambique',
    'Muso oa Lesotho': 'lesotho',
    'México': 'mexico',
    'M̧ajeļ': 'marshall islands',
    'NA': 'namibia',
    'NC': 'new caledonia',
    'NE': 'niger',
    'NF': 'norfolk island',
    'NG': 'nigeria',
    'NI': 'nicaragua',
    'NL': 'netherlands',
    'NO': 'norway',
    'NP': 'nepal',
    'NR': 'nauru',
    'NU': 'niue',
    'NZ': 'new zealand',
    'Namibia': 'namibia',
    'Namibië': 'namibia',
    'Naoero': 'nauru',
    'Nation of Brunei': 'brunei',
    'Nauru': 'nauru',
    'Naíjíríà': 'nigeria',
    'Nederland': 'netherlands',
    'Negara Brunei Darussalam': 'brunei',
    'New Zealand': 'new zealand',
    'Ngwane': 'swaziland',
    'Nicaragua': 'nicaragua',
    'Niger': 'niger',
    'Nigeria': 'nigeria',
    'Nihon': 'japan',
    'Nijar': 'niger',
    'Nijeriya': 'nigeria',
    'Nippon': 'japan',
    'Niuē': 'niue',
    'Noreg': 'norway',
    'Norfolk Island': 'norfolk island',
    'Norge': 'norway',
    'Northern Mariana Islands': 'northern mariana islands',
    'Nouvelle-Calédonie': 'new caledonia',
    'OM': 'oman',
    'Oesterreich': 'austria',
    'Oriental Republic of Uruguay': 'uruguay',
    'Osterreich': 'austria',
    'O‘zbekiston': 'uzbekistan',
    'O‘zbekiston Respublikasi': 'uzbekistan',
    'PA': 'panama',
    'PE': 'peru',
    'PF': 'french polynesia',
    'PG': 'papua new guinea',
    'PH': 'philippines',
    'PK': 'pakistan',
    'PL': 'poland',
    'PM': 'saint pierre and miquelon',
    'PN': 'pitcairn islands',
    'PR': 'puerto rico',
    'PT': 'portugal',
    'PW': 'palau',
    'PY': 'paraguay',
    'Pakistan': 'pakistan',
    'Palau': 'palau',
    'Panamá': 'panama',
    'Papua Niugini': 'papua new guinea',
    'Paraguay': 'paraguay',
    "People's Republic of Bangladesh": 'bangladesh',
    "People's Republic of China": 'china',
    'Perú': 'peru',
    'Pilipinas': 'philippines',
    'Pitcairn Henderson Ducie and Oeno Islands': 'pitcairn islands',
    'Pitcairn Islands': 'pitcairn islands',
    'Pleasant Island': 'nauru',
    'Plurinational State of Bolivia': 'bolivia',
    'Poblacht na hÉireann': 'ireland',
    'Polska': 'poland',
    'Polynésie française': 'french polynesia',
    'Portugal': 'portugal',
    'Portuguesa': 'portugal',
    'Portuguese Republic': 'portugal',
    'Prathet': 'thailand',
    'Principality of Liechtenstein': 'liechtenstein',
    'Principality of Monaco': 'monaco',
    'Principauté de Monaco': 'monaco',
    'Puerto Rico': 'puerto rico',
    'Pākistān': 'pakistan',
    'Pōrīnetia Farāni': 'french polynesia',
    'QA': 'qatar',
    'Qazaqstan': 'kazakhstan',
    'Qazaqstan Respublïkası': 'kazakhstan',
    'RE': 'réunion',
    'RO': 'romania',
    'RSA': 'south africa',
    'RU': 'russia',
    'RW': 'rwanda',
    'Ratcha Anachak Thai': 'thailand',
    'Região Administrativa Especial de Macau da República Popular da China': 'macau',
    'Reino de España': 'spain',
    'Repiblik Ayiti': 'haiti',
    'Repiblik Sesel': 'seychelles',
    "Repoblikan'i Madagasikara": 'madagascar',
    'Repubblica di San Marino': 'san marino',
    'Repubblica italiana': 'italy',
    "Repubblika ta' Malta": 'malta',
    'Republic of Armenia': 'armenia',
    'Republic of Azerbaijan': 'azerbaijan',
    'Republic of Belarus': 'belarus',
    'Republic of Benin': 'benin',
    'Republic of Botswana': 'botswana',
    'Republic of Bulgaria': 'bulgaria',
    'Republic of Burundi': 'burundi',
    'Republic of Cabo Verde': 'cape verde',
    'Republic of Cameroon': 'cameroon',
    'Republic of Chad': 'chad',
    'Republic of Chile': 'chile',
    'Republic of China': 'taiwan',
    'Republic of Colombia': 'colombia',
    'Republic of Costa Rica': 'costa rica',
    'Republic of Croatia': 'croatia',
    'Republic of Cuba': 'cuba',
    'Republic of Cyprus': 'cyprus',
    "Republic of Côte d'Ivoire": 'ivory coast',
    'Republic of Djibouti': 'djibouti',
    'Republic of Ecuador': 'ecuador',
    'Republic of El Salvador': 'el salvador',
    'Republic of Equatorial Guinea': 'equatorial guinea',
    'Republic of Estonia': 'estonia',
    'Republic of Fiji': 'fiji',
    'Republic of Finland': 'finland',
    'Republic of Guinea': 'guinea',
    'Republic of Guinea-Bissau': 'guinea-bissau',
    'Republic of Haiti': 'haiti',
    'Republic of Honduras': 'honduras',
    'Republic of Iceland': 'iceland',
    'Republic of India': 'india',
    'Republic of Indonesia': 'indonesia',
    'Republic of Iraq': 'iraq',
    'Republic of Ireland': 'ireland',
    'Republic of Kazakhstan': 'kazakhstan',
    'Republic of Kenya': 'kenya',
    'Republic of Kiribati': 'kiribati',
    'Republic of Korea': 'south korea',
    'Republic of Latvia': 'latvia',
    'Republic of Liberia': 'liberia',
    'Republic of Lithuania': 'lithuania',
    'Republic of Macedonia': 'republic of macedonia',
    'Republic of Madagascar': 'madagascar',
    'Republic of Malawi': 'malawi',
    'Republic of Mali': 'mali',
    'Republic of Malta': 'malta',
    'Republic of Mauritius': 'mauritius',
    'Republic of Moldova': 'moldova',
    'Republic of Mozambique': 'mozambique',
    'Republic of Namibia': 'namibia',
    'Republic of Nauru': 'nauru',
    'Republic of Nicaragua': 'nicaragua',
    'Republic of Niger': 'niger',
    'Republic of Palau': 'palau',
    'Republic of Panama': 'panama',
    'Republic of Paraguay': 'paraguay',
    'Republic of Peru': 'peru',
    'Republic of Poland': 'poland',
    'Republic of Rwanda': 'rwanda',
    'Republic of San Marino': 'san marino',
    'Republic of Senegal': 'senegal',
    'Republic of Seychelles': 'seychelles',
    'Republic of Sierra Leone': 'sierra leone',
    'Republic of Slovenia': 'slovenia',
    'Republic of South Africa': 'south africa',
    'Republic of Suriname': 'suriname',
    'Republic of Tajikistan': 'tajikistan',
    'Republic of Trinidad and Tobago': 'trinidad and tobago',
    'Republic of Tunisia': 'tunisia',
    'Republic of Turkey': 'turkey',
    'Republic of Uganda': 'uganda',
    'Republic of Uzbekistan': 'uzbekistan',
    'Republic of Vanuatu': 'vanuatu',
    'Republic of Zambia': 'zambia',
    'Republic of Zimbabwe': 'zimbabwe',
    'Republic of the Gambia': 'the gambia',
    'Republic of the Maldives': 'maldives',
    'Republic of the Marshall Islands': 'marshall islands',
    'Republic of the Philippines': 'philippines',
    'Republic of the Sudan': 'sudan',
    'Republica Moldova': 'moldova',
    'Republiek Suriname': 'suriname',
    'Republik Indonesia': 'indonesia',
    'Republik Singapura': 'singapore',
    'Republika Hrvatska': 'croatia',
    'Republika Slovenija': 'slovenia',
    "Republika y'Uburundi": 'burundi',
    'Republiken Finland': 'finland',
    "Repubulika y'u Rwanda": 'rwanda',
    'República Argentina': 'argentina',
    'República Bolivariana de Venezuela': 'venezuela',
    'República Democrática de São Tomé e Príncipe': 'são tomé and príncipe',
    'República Democrática de Timor-Leste': 'east timor',
    'República Dominicana': 'dominican republic',
    'República Federativa do Brasil': 'brazil',
    'República Oriental del Uruguay': 'uruguay',
    'República Portuguesa': 'portugal',
    'República da Guiné Equatorial': 'equatorial guinea',
    'República da Guiné-Bissau': 'guinea-bissau',
    'República de Angola': 'angola',
    'República de Cabo Verde': 'cape verde',
    'República de Chile': 'chile',
    'República de Colombia': 'colombia',
    'República de Costa Rica': 'costa rica',
    'República de Cuba': 'cuba',
    'República de El Salvador': 'el salvador',
    'República de Guinea Ecuatorial': 'equatorial guinea',
    'República de Honduras': 'honduras',
    'República de Moçambique': 'mozambique',
    'República de Nicaragua': 'nicaragua',
    'República de Panamá': 'panama',
    'República del Ecuador': 'ecuador',
    'República del Paraguay': 'paraguay',
    'Repúblika Demokrátika Timór-Leste': 'east timor',
    'Repúblika ng Pilipinas': 'philippines',
    'Respublika Belarus’': 'belarus',
    'Respublika Kazakhstan': 'kazakhstan',
    'Reunion': 'réunion',
    'Ribaberiki Kiribati': 'kiribati',
    'Ripablik blong Vanuatu': 'vanuatu',
    'Ripublik Naoero': 'nauru',
    'România': 'romania',
    'Rossiya': 'russia',
    'Rossiyskaya Federatsiya': 'russia',
    'Roumania': 'romania',
    'Royaume de Belgique': 'belgium',
    'Rumania': 'romania',
    'Russian Federation': 'russia',
    'Rwanda': 'rwanda',
    'Rzeczpospolita Polska': 'poland',
    'République Gabonaise': 'gabon',
    'République Togolaise': 'togo',
    'République centrafricaine': 'central african republic',
    "République d'Haïti": 'haiti',
    "République de Côte d'Ivoire": 'ivory coast',
    'République de Djibouti': 'djibouti',
    'République de Guinée': 'guinea',
    'République de Guinée équatoriale': 'equatorial guinea',
    'République de Madagascar': 'madagascar',
    'République de Maurice': 'mauritius',
    'République de Vanuatu': 'vanuatu',
    'République des Seychelles': 'seychelles',
    'République du Burundi': 'burundi',
    'République du Bénin': 'benin',
    'République du Cameroun': 'cameroon',
    'République du Congo': 'republic of the congo',
    'République du Mali': 'mali',
    'République du Niger': 'niger',
    'République du Rwanda': 'rwanda',
    'République du Sénégal': 'senegal',
    'République du Tchad': 'chad',
    'République démocratique du Congo': 'democratic republic of the congo',
    'République française': 'france',
    'SA': 'saudi arabia',
    'SB': 'solomon islands',
    'SC': 'seychelles',
    'SD': 'sudan',
    'SE': 'sweden',
    'SG': 'singapore',
    'SH': 'saint helena',
    'SI': 'slovenia',
    'SJ': 'svalbard and jan mayen',
    'SK': 'slovakia',
    'SL': 'sierra leone',
    'SM': 'san marino',
    'SN': 'senegal',
    'SO': 'somalia',
    'SR': 'suriname',
    'SS': 'south sudan',
    'ST': 'são tomé and príncipe',
    'SV': 'el salvador',
    'SY': 'syria',
    'SZ': 'swaziland',
    'Saint Helena': 'saint helena',
    'Saint Kitts and Nevis': 'saint kitts and nevis',
    'Saint Lucia': 'saint lucia',
    'Saint Vincent and the Grenadines': 'saint vincent and the grenadines',
    'Saint-Pierre-et-Miquelon': 'saint pierre and miquelon',
    'Sakartvelo': 'georgia',
    'Salṭanat ʻUmān': 'oman',
    'Samoa': 'samoa',
    'San Marino': 'san marino',
    'Sankattan Siha Na Islas Mariånas': 'northern mariana islands',
    'Sarnam': 'suriname',
    'Sathalanalat Paxathipatai Paxaxon Lao': 'laos',
    'Schweiz': 'switzerland',
    'Seychelles': 'seychelles',
    'Shqipnia': 'albania',
    'Shqipëri': 'albania',
    'Shqipëria': 'albania',
    'Sierra Leone': 'sierra leone',
    'Singapore': 'singapore',
    'Singapura': 'singapore',
    'Slovak Republic': 'slovakia',
    'Slovenija': 'slovenia',
    'Slovensko': 'slovakia',
    'Slovenská republika': 'slovakia',
    'Socialist Republic of Vietnam': 'vietnam',
    'Solomon Islands': 'solomon islands',
    'Somers Isles': 'bermuda',
    'Soomaaliya': 'somalia',
    'South Africa': 'south africa',
    'South Georgia': 'south georgia',
    'South Georgia and the South Sandwich Islands': 'south georgia',
    'South Sudan': 'south sudan',
    'Sranangron': 'suriname',
    'State of Eritrea': 'eritrea',
    'State of Israel': 'israel',
    'State of Kuwait': 'kuwait',
    'State of Libya': 'libya',
    'State of Qatar': 'qatar',
    'Suid-Afrika': 'south africa',
    'Suisse': 'switzerland',
    'Sultanate of Oman': 'oman',
    'Suomen tasavalta': 'finland',
    'Suomi': 'finland',
    'Suriname': 'suriname',
    'Svalbard and Jan Mayen Islands': 'svalbard and jan mayen',
    'Svalbard og Jan Mayen': 'svalbard and jan mayen',
    'Sverige': 'sweden',
    'Svizra': 'switzerland',
    'Svizzera': 'switzerland',
    'Swatini': 'swaziland',
    'Swaziland': 'swaziland',
    'Swiss Confederation': 'switzerland',
    'Syrian Arab Republic': 'syria',
    'São Tomé e Príncipe': 'são tomé and príncipe',
    'Sénégal': 'senegal',
    'Sāmoa Amelika': 'american samoa',
    'TD': 'chad',
    'TF': 'french southern and antarctic lands',
    'TG': 'togo',
    'TH': 'thailand',
    'TJ': 'tajikistan',
    'TK': 'tokelau',
    'TL': 'east timor',
    'TM': 'turkmenistan',
    'TN': 'tunisia',
    'TO': 'tonga',
    'TR': 'turkey',
    'TT': 'trinidad and tobago',
    'TV': 'tuvalu',
    'TW': 'taiwan',
    'TZ': 'tanzania',
    'Taneẓroft Tutrimt': 'western sahara',
    'Tanzania': 'tanzania',
    'Tchad': 'chad',
    "Teratri of Norf'k Ailen": 'norfolk island',
    'Territoire des Terres australes et antarctiques françaises':
        'french southern and antarctic lands',
    'Territoire des îles Wallis et Futuna': 'wallis and futuna',
    'Territory of Christmas Island': 'christmas island',
    'Territory of Norfolk Island': 'norfolk island',
    'Territory of the Cocos (Keeling) Islands': 'cocos (keeling) islands',
    'Territory of the Wallis and Futuna Islands': 'wallis and futuna',
    'Tetã Paraguái': 'paraguay',
    'Tetã Volívia': 'bolivia',
    'Thai': 'thailand',
    'The Bermudas': 'bermuda',
    'The Islands of Bermuda': 'bermuda',
    'Timor-Leste': 'east timor',
    'Togo': 'togo',
    'Togolese': 'togo',
    'Togolese Republic': 'togo',
    'Tokelau': 'tokelau',
    'Tonga': 'tonga',
    'Toçikiston': 'tajikistan',
    'Trinidad and Tobago': 'trinidad and tobago',
    'Turkiye': 'turkey',
    'Tuvalu': 'tuvalu',
    'Táiwān': 'taiwan',
    'Türkiye': 'turkey',
    'Türkiye Cumhuriyeti': 'turkey',
    'Türkmenistan': 'turkmenistan',
    'UA': 'ukraine',
    'UAE': 'united arab emirates',
    'UG': 'uganda',
    'UK': 'united kingdom',
    'US': 'united states',
    'USA': 'united states',
    'UY': 'uruguay',
    'UZ': 'uzbekistan',
    'Udzima wa Komori': 'comoros',
    'Uganda': 'uganda',
    'Ukrayina': 'ukraine',
    'Umbuso waseSwatini': 'swaziland',
    'Union des Comores': 'comoros',
    'Union of the Comoros': 'comoros',
    'United Kingdom': 'united kingdom',
    'United Mexican States': 'mexico',
    'United Republic of Tanzania': 'tanzania',
    'United States': 'united states',
    'United States of America': 'united states',
    'Uruguay': 'uruguay',
    'VC': 'saint vincent and the grenadines',
    'VE': 'venezuela',
    'VN': 'vietnam',
    'VU': 'vanuatu',
    'Vanuatu': 'vanuatu',
    'Venezuela': 'venezuela',
    'Viti': 'fiji',
    'Việt Nam': 'vietnam',
    'WF': 'wallis and futuna',
    'WS': 'samoa',
    'Wai‘tu kubuli': 'dominica',
    'Wallis et Futuna': 'wallis and futuna',
    'Wuliwya': 'bolivia',
    'Wuliwya Suyu': 'bolivia',
    'YE': 'yemen',
    'YT': 'mayotte',
    'Yemeni Republic': 'yemen',
    'ZA': 'south africa',
    'ZM': 'zambia',
    'ZW': 'zimbabwe',
    'Zambia': 'zambia',
    'Zhongguo': 'china',
    'Zhonghua': 'china',
    'Zhōngguó': 'china',
    'Zhōnghuá Mínguó': 'taiwan',
    'Zhōnghuá Rénmín Gònghéguó': 'china',
    'Zimbabwe': 'zimbabwe',
    'al-Ittiḥād al-Qumurī': 'comoros',
    'al-Jumhūriyyah al-Yamaniyyah': 'yemen',
    'al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah': 'mauritania',
    'al-Jumhūriyyah at-Tūnisiyyah': 'tunisia',
    'al-Mamlakah al-Urdunīyah al-Hāshimīyah': 'jordan',
    'aṣ-Ṣūmāl': 'somalia',
    'ilaṅkai': 'sri lanka',
    'weSwatini': 'swaziland',
    'Çumhuriyi Toçikiston': 'tajikistan',
    'Éire': 'ireland',
    'Ísland': 'iceland',
    'Österreich': 'austria',
    'Česko': 'czech republic',
    'Česká republika': 'czech republic',
    'śrī laṃkāva': 'sri lanka',
    "ʁɛpublika de an'ɡɔla": 'angola',
    'ʼbrug-yul': 'bhutan',
    'ʾErtrā': 'eritrea',
    'ʾĪtyōṗṗyā': 'ethiopia',
    'Ελλάδα': 'greece',
    'Ελληνική Δημοκρατία': 'greece',
    'Κυπριακή Δημοκρατία': 'cyprus',
    'Κύπρος': 'cyprus',
    'Ўзбекистон Республикаси': 'uzbekistan',
    'Белару́сь': 'belarus',
    'Белоруссия': 'belarus',
    'Босна и Херцеговина': 'bosnia and herzegovina',
    'България': 'bulgaria',
    'Казахстан': 'kazakhstan',
    'Киргизия': 'kyrgyzstan',
    'Кыргыз Республикасы': 'kyrgyzstan',
    'Кыргызстан': 'kyrgyzstan',
    'Македонија': 'republic of macedonia',
    'Монгол улс': 'mongolia',
    'Република България': 'bulgaria',
    'Република Македонија': 'republic of macedonia',
    'Республика Беларусь': 'belarus',
    'Республика Казахстан': 'kazakhstan',
    'Российская Федерация': 'russia',
    'Россия': 'russia',
    'Тоҷикистон': 'tajikistan',
    'Україна': 'ukraine',
    'Қазақстан': 'kazakhstan',
    'Қазақстан Республикасы': 'kazakhstan',
    'Ҷумҳурии Тоҷикистон': 'tajikistan',
    'Հայաստան': 'armenia',
    'Հայաստանի Հանրապետություն': 'armenia',
    'יִשְׂרָאֵל': 'israel',
    'افغانستان': 'afghanistan',
    'الأردن': 'jordan',
    'الجزائر': 'algeria',
    'السودان': 'sudan',
    'الصحراء الغربية': 'western sahara',
    'العراق': 'iraq',
    'العربية السعودية': 'saudi arabia',
    'الكويت': 'kuwait',
    'المغرب': 'morocco',
    'اليَمَن': 'yemen',
    'تونس': 'tunisia',
    'دولة الإمارات العربية المتحدة': 'united arab emirates',
    'سوريا': 'syria',
    'عمان': 'oman',
    'قطر': 'qatar',
    'لبنان': 'lebanon',
    'مصر\u200e': 'egypt',
    'موريتانيا': 'mauritania',
    'नेपाल': 'nepal',
    'भारत': 'india',
    'বাংলাদেশ': 'bangladesh',
    'ประเทศไทย': 'thailand',
    'ราชอาณาจักรไทย': 'thailand',
    'ສປປລາວ': 'laos',
    'საქართველო': 'georgia',
    'ሃገረ ኤርትራ': 'eritrea',
    'ኢትዮጵያ': 'ethiopia',
    'ኤርትራ': 'eritrea',
    'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ': 'ethiopia',
    '\u200fالبحرين': 'bahrain',
    '\u200fليبيا': 'libya',
    '中华人民共和国': 'china',
    '中国': 'china',
    '中華人民共和國澳門特別行政區': 'macau',
    '中華民國': 'taiwan',
    '新加坡共和国': 'singapore',
    '日本': 'japan',
    '澳門': 'macau',
    '澳门': 'macau',
    '臺灣': 'taiwan',
    '香港': 'hong kong',
    '대한민국': 'south korea',
    '북한': 'north korea',
    '조선민주주의인민공화국': 'north korea'}

lowercase_country_dict = {x.lower(): y for x, y in country_dict.items()}
